In [ ]:
a = 10
b = 20

a = str(a)
b = str(b)
print("{}".format(a+b))

# print(??)
# 출력 => 1020

1020

In [ ]:
a = '3'
b = '6'

a = int(a)
b = int(b)

print(a+b)
# 출력 9

9

In [ ]:
a = '3.1'
b = '6.1'

a = float(a)
b = float(b)

print(a + b)
# 출력 9.2

9.2

In [ ]:
a = '3.1'
b = '6.1'

a = float(a)
b = float(b)

print("{0:.0f}".format(a+b))
# 출력 9

9

In [ ]:
# list(리스트)

# 변수는 하나의 데이터만 담을 수 있다.
# 여러개의 데이터를 한번에 이동시키면 편할 텐데

# 시나리오 : 인명부(이름, 나이, 번호, 이메일)

name = ["홍길동","홍길순","박철민"]
ages = [10,20,30]

ages2 = ages
ages3 = ages

print("ages : ", id(ages))
print("ages2 : ", id(ages2))
print("ages3 : ", id(ages3))

print(id([10,20,30]))

print(ages[0])
print(ages2[0])
print(ages3[0])


# 인덱스 : 데이터의 위치, 자동부여

print(name[0])
print(ages[0])

ages :  139156341648704
ages2 :  139156341648704
ages3 :  139156341648704
139156368137664
10
10
10
홍길동
10

In [ ]:
a = 10
b = a
print(id(a))
print(id(b))

obj = [10,20,30]
obj2 = obj

print("리모컨 복제")
print(id(obj))
print(id(obj2))

obj2[1] = 99
print("복제한 리모컨으로 수정")
print(id(obj))
print(id(obj2))

print(obj)
print(obj2)

139156798734864
139156798734864
리모컨 복제
139156368209792
139156368209792
복제한 리모컨으로 수정
139156368209792
139156368209792
[10, 99, 30]
[10, 99, 30]

In [ ]:
# 리스트 활용

# 데이터 추가 / 읽기 / 수정 / 삭제 (feat.CRUD : create, read, update, delete)

# 객체 생성
obj = []
print("객체 생성 : ", obj)
# 추가 : .append()
obj.append(123)
print("데이터 추가 후: ",obj)
obj.append(888)
obj.append(2)
obj.append(56)
print("데이터 추가 후: ",obj)


# 수정 : 인덱스 찾아서 변수 수정하듯
# 인덱스는 리스트 데이터 방의 번호. 0부터 자동부여
obj[0] # 리스트의 0번째 데이터를 가져온다
print("obj 0번 인덱스의 데이터 : ",obj[0])

obj[0] = 99 # 0번째 데이터 수정
print("obj 0번 인덱스의 데이터 : ",obj[0])
print(obj)


# 삭제 : .remove(), del
# 삭제를 하면 남은 데이터들은 0번 인덱스부터 재정렬

obj.remove(99) # 어떤 데이터를 삭제할 지 결정
print("obj 99 삭제 후 : ", obj)

del obj[3] # 인덱스로 찾은 데이터 삭제
print("obj 3번 인덱스 삭제 후 : ", obj)

데이터 추가 후 :  [123]
데이터 추가 후 :  [123, 888]
데이터 추가 후 :  [123, 888, 2]
데이터 추가 후 :  [123, 888, 2, 65]
obj의 0 번째 데이터 123
obj의 0 번째 데이터 수정후 999
obj 999 삭제 후 :  [888, 2, 65]
obj의 0번쨰 데이터 삭제 후 :  [2, 65]

In [ ]:
# 문제 : 리스트에 순서대로 2, 1, 5, 6, 7를 한번에 담아주세요.

week = [2,1,5,6,7]
print(week)

[2, 1, 5, 6, 7]

In [ ]:
# 문제 : 비어있는 리스트를 만들고, 순서대로 2, 1, 5, 6, 7를 하나씩 담아주세요.

week2 = []

week2.append(2)
week2.append(1)
week2.append(5)
week2.append(6)
week2.append(7)

print(week2)

[2, 1, 5, 6, 7]

In [ ]:
# 문제 : 리스트에 순서대로 '월', '화', '수', '목', '금'을 한번에 담아주세요. 그리고 '토', '일' 을 순서대로 추가해주세요.

week = ["월","화","수","목","금"]

week.append("토")
week.append("일")

print(week)

['월', '화', '수', '목', '금', '토', '일']

In [ ]:
# 문제 : 리스트에 순서대로 '월', '화', '수', '목', '금'을 한번에 담아주세요. 그리고 '토', '일' 을 담은 리스트를 만들고 2개의 리스트 합쳐서 새로운 리스트를 만들어주세요.

week = ["월","화","수","목","금"]

week2 = ["토","일"]

week3 = week+week2

print(week3)

['월', '화', '수', '목', '금', '토', '일']

In [ ]:
# 문제 : 리스트에 순서대로 '월', '화', '수', '목', '금'을 한번에 담아주세요. 그리고 '+=' 연산자를 이용해서 '토', '일' 을 한번에 추가해주세요.



week = ["월","화","수","목","금"]

week += ["토","일"]

print(week)

['월', '화', '수', '목', '금', '토', '일']

In [ ]:
# 문제 : 리스트에 순서대로 '월', '화', '수', '목', '금'을 한번에 담아주세요. 그리고 가장 처음 요소를 출력해주세요.

week = ["월","화","수","목","금"]

print(week[0])

월

In [ ]:
# 문제 : 리스트에 순서대로 '월', '화', '수', '목', '금'을 한번에 담아주세요. 그리고 가장 마지막 요소를 출력해주세요.

week = ["월","화","수","목","금"]

print(week[4])
print(week[-1])
print(week[len(week)-1])

금
금
금

In [ ]:
# 문제 : 리스트에 순서대로 '월', '화', '수', '목', '금'을 한번에 담아주세요. 그리고 가장 마지막에서 2번째 요소를 출력해주세요.

week = ["월","화","수","목","금"]

print(week[3])
print(week[-2])
print(week[len(week)-2])

목
목
목

In [62]:
# 문제 : 리스트에 순서대로 '월', '화', '수', '목', '금'을 한번에 담아주세요. 그리고 while문을 이용해서 요소 전부 출력해주세요.

week = ["월","화","수","목","금"]

i = 0
while i < len(week):
  print(week[i])
  i+=1

월
화
수
목
금

In [84]:
# 문제 : 리스트에 순서대로 '월', '화', '수', '목', '금'을 한번에 담아주세요. 그리고 while문을 이용해서 요소 전부 역순으로 출력해주세요

week = ["월","화","수","목","금"]

i = len(week)-1
while i >= 0:
  print(week[i])
  i -= 1

금
목
수
화
월

In [82]:
# 문제 : 리스트에 순서대로 2, 1, '오', 6, 7를 한번에 담아주세요. 그리고 리스트 안에 있는 '오'를 정수 5로 변경해주세요.

qwer = [1,2,"오",6,7]

qwer[2] = 5

print(qwer)

[1, 2, 5, 6, 7]

In [83]:
# 문제 : 리스트에 순서대로 2, 1, '오', 6, 7를 한번에 담아주세요. 그리고 리스트 안에 있는 '오'를 제거해주세요.

qwer = [1,2,"오",6,7]

del qwer[2]

print(qwer)

[1, 2, 6, 7]

In [98]:
# 문제 : 리스트에 순서대로 '월', '화', '수', '목', '금'을 한번에 담아주세요. '화'가 리스트 안에서 몇 번째 데이터 인지 알려주세요.

week = ["월","화","수","목","금"]

print(week.index("화"))

1

In [100]:
# 문제 : 리스트에 순서대로 '월', '화', '수', '목', '금'을 한번에 담아주세요. '화'가 리스트 안에 있는지 if문으로 체크 후, 있다면 삭제해주세요.

week = ["월","화","수","목","금"]
if "화" in week:
  print("있다")
  week.remove("화")
else:
  print("없다")

있다

In [99]:
# 문제 : 리스트에 순서대로 '월', '화', '수', '목', '금'을 한번에 담아주세요. '토'가 리스트 안에 있는지 if문으로 체크 후, 있다면 삭제해주세요

week = ["월","화","수","목","금"]
if "토" in week:
  print("있다")
  week.remove("토")
else:
  print("없다")

없다

In [106]:
# 문제 : 리스트에 순서대로 '월', '화', '수', '목', '금'을 한번에 담아주세요. 리스트에 있는 '금'을 삭제하는 3가지 방법을 보여주세요

week = ["월","화","수","목","금"]

# del week[-1]
# del week[len(week)-1]
week.remove("금")
print(week)

['월', '화', '수', '목']

In [111]:
# 문제 : 리스트에 순서대로 '월', '화', '수', '목', '금'을 한번에 담아주세요. 리스트에 있는 '금'을 안전하게 삭제하는 2가지 방법을 보여주세요.

week = ["월","화","수","목","금"]

# del week[week.index("금")]

if "금" in week:
  week.remove("금")


print(week)

['월', '화', '수', '목']

In [114]:
# 문제 - 1부터, 10까지 리스트로 묶어주세요

# num = [1,2,3,4,5,6,7,8,9,10]

num=[]
i= 1
while i <= 10:
  num.append(i)
  i+=1

print(num)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]